### PR TITLE
Bugfix: Referrers doc titles

### PR DESCRIPTION
**Pull request by Maaiins**
The http client returns can´t connect to the host to crawl page titles. I updated the http client library to solve this issue.

Ref: #177 #443

### CODE REVIEW

**Comment by padams** [comment]
I think it might make sense to remove the test scripts for this http library from OWA. Especially the yahoo stuff. thoughts?

**Comment by Maaiins** [comment]
Yeah would be good, didn't thought about this. I´m doing this quick

**Comment by padams** [comment]
don't forget test_http.php and that gif file...

**Comment by Maaiins** [comment]
I removed the gif. test_http is already removed

**Pull request merged**
