### PR TITLE
Bugfix: Secondary dimension joins

### PR DESCRIPTION
**Pull request by Maaiins**
Ref: #469

### CODE REVIEW

**Comment by padams** [comment]
Another great catch. Looks like inbound_visitor_id was a hold over concept from a time long before we refactored fact table entities. Now all fact entities have an automatic foreign key added to them based on the visitor_id.

We should probably look to drop the inbound_visitor_id column from the schema at some point just to avoid future confusion.

**Comment by Maaiins** [comment]
Sounds great I found some weird relations in the database. But I dont wanted do re engineer it by myself. So we can do this in future, I will help you but I need your assistance and know how.
I can write the database updates and table migrations for old installations.

**Comment by padams** [comment]
Do you want to start a ticket for this and we can discuss there?

**Comment by Maaiins** [comment]
Done ;-)

**Pull request merged**
